### ISSUE TITLE
2 IOS cannot pair with one device

### ISSUE THREAD

**Issue by FFTSolution** [Mixiaoxiao/Arduino-HomeKit-ESP32#2]
Hi @Mixiaoxiao .
 I have problem with this library.
when the fist IOS device pairs with ESP8266 homeKit, the second IOS device not pair with it ?
can u solve this problem ? Thanks you !

**Comment by Mixiaoxiao** [comment]
True. Not an issue.
See [https://github.com/Mixiaoxiao/Arduino-HomeKit-ESP8266/issues/10#issuecomment-613969645](https://github.com/Mixiaoxiao/Arduino-HomeKit-ESP8266/issues/10#issuecomment-613969645)

**Comment by Mixiaoxiao** [comment]
Not an issue and will be closed soon.
